#############################################
#   author:ross                             #
#   mail:yesterday679@gmail.com             #
#   time:2017/02/20                         #
#   description:docker compose              #
#############################################
version: '2'

services:

  ######## drivers ########
  drivers:
    image: tianon/true
    volumes:
      - C:/www/:/var/www/html


  ######## php-fpm ########
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        - INSTALL_MYSQLI=true
        - INSTALL_PDO_MYSQL=true
        - INSTALL_SWOOLE=true
        - INSTALL_REDIS=true
        - INSTALL_OPCACHE=true
        - INSTALL_PCNTL=true
        - INSTALL_IMAGICK=false
        - INSTALL_GD=true
        - INSTALL_MSGPACK=false
        - INSTALL_XDEBUG=true
        - INSTALL_SOAP=false
        - INSTALL_MONGO=false
        - INSTALL_ZIP_ARCHIVE=false
        - INSTALL_BCMATH=false
        - INSTALL_MEMCACHED=false
        - INSTALL_XHPROF=false
        - CODEIGNITER=false
    volumes_from:
      - drivers
    expose:
      - "9000"
    environment:
      XDEBUG_CONFIG: "remote_host=170.240.100.122"
      PHP_IDE_CONFIG: "serverName=yesterday679.com"


  ######## nginx ########
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - drivers
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/ssl/:/etc/ssl
      - ./nginx/config/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm


  ######## mysql ########
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
          - MYSQL_USER=ross
          - MYSQL_PASSWORD=ross
          - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"


  ######## redis ########
  redis:
    build:
      context: ./redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  ######## openresty ########
  openresty:
    build:
      context: ./openresty
    volumes_from:
      - drivers
    volumes:
      - ./logs/openresty/:/usr/local/openresty/nginx/logs
      - ./openresty/conf/:/usr/local/openresty/nginx/conf.d
    ports:
      - "8888:8888"


volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
